# Generated by Django 2.2.5 on 2021-04-19 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Enter a portfolio name (e.g. Andras portfolio', max_length=200)),
                ('trade_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('cutip', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(help_text='Look up the ticker manually now', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Enter a cryptocurrency (e.g. Bitcoin', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trade_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_currency', models.DecimalField(decimal_places=0, max_digits=10)),
                ('date', models.DateField()),
                ('cutip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aladdin.Security')),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aladdin.Portfolio')),
            ],
        ),
    ]
