# Generated by Django 2.2.5 on 2021-04-23 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='cutip',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
