# Generated by Django 2.2.5 on 2021-04-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='trade_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='security',
            name='name',
            field=models.CharField(help_text='Enter a cryptocurrency name (e.g. Bitcoin)', max_length=200),
        ),
    ]
