# Generated by Django 2.2.5 on 2021-04-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0002_auto_20210419_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='trade_id',
        ),
    ]
