# Generated by Django 2.2.5 on 2021-04-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0002_auto_20210423_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='cutip',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Portfolio_View',
            fields=[
                ('cutip', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('portfolio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aladdin.Portfolio')),
            ],
        ),
    ]
