# Generated by Django 3.1 on 2021-05-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0002_delete_portfolioview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
