# Generated by Django 2.2.5 on 2021-04-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0003_auto_20210423_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(to='aladdin.Coin'),
        ),
        migrations.DeleteModel(
            name='Portfolio_View',
        ),
    ]
