# Generated by Django 2.2.5 on 2021-04-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0003_remove_portfolio_trade_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='security',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='security',
            name='cutip',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
