# Generated by Django 2.2.5 on 2021-04-19 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0004_auto_20210419_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='number_of_currency',
            new_name='number_of_coins',
        ),
    ]
