# Generated by Django 2.2.5 on 2021-04-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0005_remove_portfolio_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='coins',
            field=models.ManyToManyField(to='aladdin.Coin'),
        ),
    ]
