# Generated by Django 2.2.5 on 2021-04-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aladdin', '0006_portfolio_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='coins',
        ),
    ]
